//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CapstoneEntities : DbContext
    {
        public CapstoneEntities()
            : base("name=CapstoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LevelOfFitness> LevelOfFitnesses { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<ExerciseType> ExerciseTypes { get; set; }
        public virtual DbSet<UserExerciseType> UserExerciseTypes { get; set; }
        public virtual DbSet<GymOrPlace> GymOrPlaces { get; set; }
        public virtual DbSet<GymUser> GymUsers { get; set; }
        public virtual DbSet<NearByZip> NearByZips { get; set; }
    
        public virtual ObjectResult<FindNearbyUsers_Result> FindNearbyUsers(Nullable<int> searchZipCode)
        {
            var searchZipCodeParameter = searchZipCode.HasValue ?
                new ObjectParameter("SearchZipCode", searchZipCode) :
                new ObjectParameter("SearchZipCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindNearbyUsers_Result>("FindNearbyUsers", searchZipCodeParameter);
        }
    }
}
