//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExerciseType
    {
        public int UserExerciseTypeID { get; set; }
        public string UserID { get; set; }
        public int ExerciseTypeID { get; set; }
        public Nullable<int> GymID { get; set; }
        public int LevelID { get; set; }
    
        public virtual ExerciseType ExerciseType { get; set; }
        public virtual LevelOfFitness LevelOfFitness { get; set; }
        public virtual GymOrPlace GymOrPlace { get; set; }
        public virtual GymUser GymUser { get; set; }
    }
}
